### ISSUE TITLE
Should `att` be required ?

### ISSUE THREAD

**Issue by Gozala** [ucan-wg/spec#105]
I just noticed that spec states that `att` is optional, which seems odd. What would be the use case for the UCAN which does not delegate any capabilities ?

If there is no real use case for it should it be made mandatory ?

**Comment by expede** [comment]
You can use UCAN to prove that you have access to something without delegating capabilities, sign challenges, and so on. We use this in AWAKE, for instance.

I agree that the field should be mandatory, and `[]` in the (e.g.) AWAKE case. Will fix 👍
