### ISSUE TITLE
Can there be some examples in `3.2.5 Attenuation`?

### ISSUE THREAD

**Issue by gobengo** [ucan-wg/spec#135]
A couple times now I've seen `"att":` in the wild, and I try to search the ucan spec for `"att"` and find nothing. I think [section 3.2.5](https://github.com/ucan-wg/spec#325-attenuation) is what describes that fields contents (right?), and if so, one or more examples would make the spec more understandable in this context.

**Comment by expede** [comment]
<img width="720" alt="Screenshot 2022-11-28 at 10 36 43" src="https://user-images.githubusercontent.com/1052016/204354545-8ca58c94-5780-4757-9ffd-0a011de8b2da.png">


OMG 🤦‍♀️ The _core_ thing is not in the table. Thanks @gobengo, will fix.

**Comment by expede** [comment]
Wait, no it's in there! Why isn't it showing up in a CMD-F search? At minimum, this needs to be made more salient

**Comment by matheus23** [comment]
Yeah agreed. There's a list of example *capabilities* here: https://github.com/ucan-wg/spec#242-examples (Under 2.4 Capabilities), and `att` is just a list of these.
(The linked example is a list of capabilities, too.)

It'd probably be useful to have such examples in the `att` section, too.

**Comment by expede** [comment]
Closed by #132
