### ISSUE TITLE
Clarify semantics of `OWN`

### ISSUE THREAD

**Issue by bumblefudge** [ucan-wg/spec#141]
I've re-read [this section](https://github.com/ucan-wg/spec/blob/692e8aab59b763a783fe1484131c3f40d997b69a/README.md#42-own) a few times and I'm not 100% clear I got it.  Is it a protocol-specific wildcard?  Does own://did:example:me/mailto mean "any email address did:example:me controls?" or "any email address did:example:me can prove they control at decision time", etc ?  Might help to add an example and/or a tiny bit more non-normative text there for goofballs like me

**Comment by gobengo** [comment]
same, I don't really get it or how to interop with or test it

**Comment by expede** [comment]
Closed by #132
