### ISSUE TITLE
Update raw data multicodec link

### ISSUE THREAD

**Issue by bgins** [ucan-wg/spec#164]
The link in the spec currently points to the `protobuf` entry in the multicodec table: https://github.com/ucan-wg/spec/blob/b172154d76d893a7fdb9376d7c28800ee79b0965/README.md?plain=1#L1080

Likely the entries in the table shifted around. We should update the link or maybe avoid referencing by line.

**Comment by bumblefudge** [comment]
![image](https://github.com/ucan-wg/spec/assets/37127325/48e659a6-d67f-4797-bc75-c9223b8831a0)

Would the [commit-specific link](https://github.com/multiformats/multicodec/blob/a03169371c0a4aec0083febc996c38c3846a0914/table.csv#L39) work? It ain't 100% future-proof but it will get us through the coming years (including the overhaul of the multiformats repos that might be coming in what remains of 2023)
