### ISSUE TITLE
Please add version tags to the repo

### ISSUE THREAD

**Issue by Peeja** [ucan-wg/spec#182]
It's getting tricky to refer back to older versions of the spec, which is important to be able to do as the spec changes so quickly. Having at least the more recent versions of the spec tagged in the repo would help a lot. I've pulled out the commits that appear to be versions:

* [v1.0-rc.1](https://github.com/ucan-wg/spec/commit/1c64556f15574af80022bf38b6f4b3125696eae9)
* [v0.10](https://github.com/ucan-wg/spec/commit/04f46205f0e2be64c96e0b69bf44bfcd8fc8e006)
* [v0.9.2](https://github.com/ucan-wg/spec/commit/692e8aab59b763a783fe1484131c3f40d997b69a)
* [v0.9.0](https://github.com/ucan-wg/spec/commit/db746f89ade11487b7939c381f23b1b7d9efe8e0)

**Comment by icidasset** [comment]
Good shout, added tags for the first three you listed. If someone needs the older ones, ping me and I'll add the rest.

**Comment by Peeja** [comment]
Thank you!
