### ISSUE TITLE
Clarify activities and actors in Section 5.2

### ISSUE THREAD

**Issue by csuwildcat** [ucan-wg/spec#32]
In section 5.2, the terminology around who/to/from the 'discharching' party/agent is vs the validating or invoking parties are isn't clear (at least to a couple of us who read it): https://github.com/ucan-wg/spec#52-principal-alignment. Is there any way to get a graphic or multi-part example that shows Alice issuing a capability to Bob with an invocation of it against some validating party who has the ability to assess and allow it?

**Comment by expede** [comment]
@csuwildcat yep sure thing!

**Comment by expede** [comment]
@csuwildcat in theory the new diagram should help clarify. _Please do_ let me know if it didn't clarify what you were asking :)

**Comment by csuwildcat** [comment]
Looks good now!
