### ISSUE TITLE
Have existing contributors sign the CLA

### ISSUE THREAD

**Issue by expede** [ucan-wg/spec#48]
Hey existing contributors 👋 Thank you so much for your work on this repo so far!

# What is an IPR?

We're doing an intellectual propert release (IPR) process. This essentially protects downstream projects that depend on UCAN  from us patenting the ideas in this spec and suing them patent-troll style. We're "releasing the spec into the community" rather than owning it individually.

It's a prereq for UCAN gaining adoption with larger projects & companies. We also need this as "hygiene" if we later move the spec inside the IETF, W3C, DIF, etc. Basically it's much easier to do early and enforce it, than when you have dozens/hundreds/thousands of people to track down. OAuth went through the exact same process early on (though with their own hand-rolled IPR docs).

# How Do?

The good news is that this is extremely straightforward. With the magic of GitHub PRs, we can use a commit/PR to "sign" the IPR. Here's an example PR from @bgins https://github.com/ucan-wg/spec/pull/46/files. It's two files.

If you want to see the full text of what you're signing, it's in these files:

* https://github.com/ucan-wg/spec/blob/main/Community_Specification_License-v1.md
* https://github.com/ucan-wg/spec/blob/main/Notices.md

# What If I Don't Want To?

If you don't agree with IPRing the spec, that's no problem. Please let us know, and we will remove your existing commits and discussion comments.

# CLA Progress

* [x] @appcypher 
* [x] @b5 
* [x] @bgins
* [x] @bmann
* [x] @dholms 
* [x] @expede 
* [x] @gobengo 
* [x] @Gozala 
* [x] @matheus23 
* [ ] @mistermoe 
* [x] @QuinnWilton

**Comment by expede** [comment]
Hey @gobengo 👋 Could I bother you for an IPR signature? It's really quick, I promise! Here's an example: https://github.com/ucan-wg/spec/pull/58/files Thank you 🙏

**Comment by gobengo** [comment]
@expede sure thing. wdyt of https://github.com/ucan-wg/spec/pull/74 ?
