### ISSUE TITLE
spec incompatible test fixture

### ISSUE THREAD

**Issue by Gozala** [ucan-wg/spec#68]
This fixture seems to be incompatible with a spec

https://github.com/ucan-wg/spec/blob/76e91bd9da67cf796f04760372fe1894e58b1480/fixtures/0.8.1/valid.json#L207-L208

As I understand it it should be `prf:0` instead per
https://github.com/ucan-wg/spec#prf-scheme

**Comment by expede** [comment]
Indeed. Will fix; thanks!
