### ISSUE TITLE
v0.8 test fixtures

### ISSUE THREAD

**Issue by expede** [ucan-wg/spec#7]
Generate valid and invalid example UCANs to test implementations against. At least one per failure type (e.g. rights escalation), and one valid per key type and feature (root UCAN, single vs multiple capabilities, and so on).

The Haskell UCAN codebase can generate random UCANs on the fly (via QuickCheck) so it may be easiest to generate them there.

**Comment by expede** [comment]
@appcypher I saw you asking where the fixtures lived on Discord. Because we have multiple implementations, we create fixtures themselves in the `ucan-wg/spec` repo (e.g. [`tests/0.7` fixtures](https://github.com/ucan-wg/spec/tree/main/tests/0.7.0)), labelled by how they're broken (or not broken, depending). Implementers can then write tests against these.

**Comment by appcypher** [comment]
@expede The Haskell UCAN codebase you mentioned above, is it [fission/hs-ucan](https://github.com/fission-suite/fission/tree/main/hs-ucan)?

**Comment by expede** [comment]
@appcypher it is, yes. @matheus23 currently has the hood up on it, but it will move to `ucan-wg` in the near future :)

**Comment by expede** [comment]
Probably worth mentioning that `hs-ucan` will generate _valid_ UCANs only, which you'd need to "break" by hand for test cases.
