### ISSUE TITLE
Require that versions "increase monotonically" in the UCAN chains

### ISSUE THREAD

**Issue by matheus23** [ucan-wg/spec#9]
When delegating some capabilities from a UCAN with version, say `0.5.0`, you *must* use UCAN version *at least* `0.5.0`.

Most of the reason is "why not?": Whoever you are, you seem to be able to understand at least version 0.5.0, so why create some earlier version? Also, whoever you seem to talk to using that UCAN, they *must* be able to understand version 0.5.0 to understand the whole chain anyway also.

The remaining reason is allowing to change the semantics of UCANs in a way that restricts what rights a UCAN has in newer versions. The problem with that without this proposal is that anyone would be able to create an "old" UCAN with "more" rights again, cheating the UCAN upgrade.

This essentially prepares us for such kinds of upgrades.

**Comment by expede** [comment]
Closed by #10
